from tortoise import Model, fields


class ModelTools(Model):
    id = fields.IntField(pk=True)
    consecutive= fields.IntField()
    code = fields.CharField(max_length=30, unique=True)
    code_dane = fields.CharField(max_length=10, null=True)
    code_last = fields.CharField(max_length=30, null=True)
    hours_work = fields.IntField(null=True)
    date_make = fields.DateField(null=True)
    brand = fields.CharField(max_length=75, null=True)
    model = fields.CharField(max_length=100, null=True)
    colour = fields.CharField(max_length=75, null=True)
    clas = fields.CharField(max_length=75, null=True)
    batch = fields.CharField(max_length=50, null=True)
    location = fields.CharField(max_length=100, null=True)
    pipe_allowed = fields.CharField(max_length=100, null=True)
    plate = fields.CharField(max_length=7, null=True)
    description = fields.CharField(max_length=100, null=True)
    capacity = fields.CharField(max_length=30, null=True)
    motor_number = fields.CharField(max_length=30, null=True)
    vim_number = fields.CharField(max_length=30, null=True)
    amount = fields.IntField(null=True)
    axes = fields.IntField(null=True)
    date_buy = fields.DateField()
    wire = fields.CharField(max_length=75, null=True)
    basis_weight = fields.CharField(max_length=10, null=True)
    charge_weight = fields.CharField(max_length=10, null=True)
    TP = fields.CharField(max_length=100, null=True)
    high = fields.CharField(max_length=30, null=True)
    wide = fields.CharField(max_length=30, null=True)
    long = fields.CharField(max_length=30, null=True)
    diameter = fields.CharField(max_length=30, null=True)
    coil_long = fields.IntField(null=True)
    breaking_strength = fields.IntField(null=True)
    type = fields.IntField(default=1)
    created = fields.DatetimeField(auto_now=True)
    updated = fields.DatetimeField(null=True)
    deleted = fields.DatetimeField(null=True)
    available = fields.BooleanField(default=True)
    lineservices = fields.ForeignKeyField('models.ModelLineservices')
    names = fields.ForeignKeyField('models.ModelNames')
    measures = fields.ForeignKeyField('models.ModelMeasures')
    categories = fields.ForeignKeyField('models.ModelCategories')
    companies = fields.ForeignKeyField('models.ModelCompanies')
    locations = fields.ForeignKeyField('models.ModelLocations')
    typevehicles = fields.ForeignKeyField("models.ModelTypevehicles", null=True)
    is_lift = fields.IntField(default=1)
    hv = fields.BooleanField(default=0)
    hv_created = fields.DatetimeField(null=True)
    status_general = fields.IntField(default=1)

    class Meta:
        table = 'tools'